export const newprop: any = {
    Owner: {
        name: 'Nicola Hill',
        id: '3430088000000176021',
        email: 'nicola.hill@johnhill.com.au'
    },
    Build_Area_sqm: null,
    $currency_symbol: 'AU$',
    Suburb: 'BURWOOD',
    $upcoming_activity: null,
    Latitude: '-33.8793736',
    Admin_Fields: false,
    Office_area_sqm: null,
    Unit: null,
    Last_Activity_Time: '2020-07-22T09:09:24+10:00',
    Autoupdate: true,
    Recent_Note: null,
    Water_Rates: null,
    Detailed_View: true,
    Council_Rates: null,
    $state: 'save',
    $process_flow: false,
    Deal_Name: '224 Burwood Road, BURWOOD',
    Currency: 'AUD',
    Stage: 'Leased',
    Strata_Plan: null,
    Street: 'Burwood Road',
    Sale_Price: null,
    id: '3430088000003041679',
    $approved: true,
    Street_No: '224',
    $approval: {
        delegate: false,
        approve: false,
        reject: false,
        resubmit: false
    },
    Total_Income: null,
    Building_Complex_Strata_Title_Not_Applicable: 'Torrens',
    Retail_sqm: null,
    Created_Time: '2020-04-27T11:35:40+10:00',
    Source_ID: 'P0182',
    $editable: true,
    Grade: null,
    Longitude: '151.1035655',
    Postcode: '2134',
    Land_Tax: null,
    Add_Note: null,
    Lot: null,
    State: 'NSW',
    $status: 'cmv_10-46',
    Property_Contacts: null,
    User: null,
    $photo_id: null,
    $review_process: {
        approve: false,
        reject: false,
        resubmit: false
    },
    Outgoings_Basis: null,
    Council: 'Burwood Council',
    Showroom_sqm: null,
    $review: null,
    Lead_Conversion_Time: null,
    Overall_Sales_Duration: null,
    Listing_No: '316002079',
    Property_Type_Portals: [
        'Retail'
    ],
    Known_As: null,
    Modified_Time: '2020-07-22T09:09:24+10:00',
    Prop_Zoning: 'Zone B4 - Mixed Use',
    Sale_Type: [],
    Land_Area_sqm: null,
    Car_Spaces: null,
    $orchestration: false,
    Sales_Cycle_Duration: null,
    Property_Owners: '[{"Owner":{"name":"Nicola Hill","id":"3430088000000176021","email":"nicola.hill@johnhill.com.au"},"Company":"MA And Family Pty Ltd","Email":null,"Last_Mailed":null,"Postal_Suburb":null,"$currency_symbol":"AU$","Suburb":null,"Postal_Street_No":null,"Unit":null,"Name":"MA And Family Pty Ltd","Last_Activity_Time":null,"Recent_Note":null,"$state":"save","$process_flow":false,"Work_Phone":null,"Currency":"AUD","Street":null,"Postal_State":null,"id":"3430088000003037530","$approved":true,"Postal_Postcode":null,"Postal_Address":null,"Street_No":null,"$approval":{"delegate":false,"approve":false,"reject":false,"resubmit":false},"Created_Time":"2020-04-27T13:03:20+10:00","Address_To":null,"Source_ID":"O0247","From_Ownership":null,"$editable":true,"Return_to_Sender":false,"Postcode":null,"Home_Phone":null,"Add_Note":null,"State":null,"Country":null,"Postal_Country":null,"$review_process":null,"Website":null,"Do_Not_Mail":false,"Last_Mailed_Date":null,"First_Name":null,"Record_Image":null,"$review":null,"Address_Longitude":null,"Postal_Level_Suite":null,"Email_Opt_Out":false,"Residential_Address":null,"Copy_to_Postal":false,"Address_Latitude":null,"Modified_Time":"2020-04-27T13:03:20+10:00","Salutation_Dear":null,"Postal_Street":null,"Title":null,"Return_to_Sender_Date":null,"Lessee":null,"Mobile":null,"$orchestration":null,"System_Contact":null,"Last_Name":null,"Reverse_Geocoded_Address":null,"ABN_ACN":null,"Postal_Unit":null,"Tag":[],"Level_Suite":null,"Fax":null}]',
    Sale_Date: null,
    Total_Outgoings: null,
    Reverse_Geocoded_Address: '224 Burwood Rd, Burwood NSW 2134, Australia',
    $in_merge: false,
    Insurance: null,
    Warehouse_sqm: null,
    Tag: [],
    Level_Suite: null,
    Property_Category_Mailing: [],
    Managed: null,
    Other: null,
    owner_details: [
        {
            Owner: {
                name: 'Nicola Hill',
                id: '3430088000000176021',
                email: 'nicola.hill@johnhill.com.au'
            },
            Company: 'MA And Family Pty Ltd',
            Email: null,
            Last_Mailed: null,
            Postal_Suburb: null,
            $currency_symbol: 'AU$',
            Suburb: null,
            Postal_Street_No: null,
            Unit: null,
            Name: 'MA And Family Pty Ltd',
            Last_Activity_Time: null,
            Recent_Note: null,
            $state: 'save',
            $process_flow: false,
            Work_Phone: null,
            Currency: 'AUD',
            Street: null,
            Postal_State: null,
            id: '3430088000003037530',
            $approved: true,
            Postal_Postcode: null,
            Postal_Address: null,
            Street_No: null,
            $approval: {
                delegate: false,
                approve: false,
                reject: false,
                resubmit: false
            },
            Created_Time: '2020-04-27T13:03:20+10:00',
            Address_To: null,
            Source_ID: 'O0247',
            From_Ownership: null,
            $editable: true,
            Return_to_Sender: false,
            Postcode: null,
            Home_Phone: null,
            Add_Note: null,
            State: null,
            Country: null,
            Postal_Country: null,
            $review_process: null,
            Website: null,
            Do_Not_Mail: false,
            Last_Mailed_Date: null,
            First_Name: null,
            Record_Image: null,
            $review: null,
            Address_Longitude: null,
            Postal_Level_Suite: null,
            Email_Opt_Out: false,
            Residential_Address: null,
            Copy_to_Postal: false,
            Address_Latitude: null,
            Modified_Time: '2020-04-27T13:03:20+10:00',
            Salutation_Dear: null,
            Postal_Street: null,
            Title: null,
            Return_to_Sender_Date: null,
            Lessee: null,
            Mobile: null,
            $orchestration: null,
            System_Contact: null,
            Last_Name: null,
            Reverse_Geocoded_Address: null,
            ABN_ACN: null,
            Postal_Unit: null,
            Tag: [],
            Level_Suite: null,
            Fax: null,
            Contact_Type: 'Owner'
        }
    ]
}
